services:
  docs:
    image: local_docs
    container_name: local_docs
    build:
      context: ../..
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ../../.envs/.local/.live/.app
    volumes:
      - ../../docs:/docs:z
      - ../../app/config:/app/config:z
      - ../../app:/app/app:z
    ports:
      - '9000:9000'
    command: /start-docs
